spring:
  application:
    name: booking-service
  config:
    activate:
      on-profile: kubernetes

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

greeting:
  message: "Booking-Service in Kubernetes!"