server:
  port: 0

spring:
  application:
    name: booking-service
  config:
    activate:
      on-profile: default
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: booking-service
    kubernetes:
      enabled: false
      config:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka