server:
  port: 8000
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

spring:
  config:
    activate:
      on-profile: kubernetes
  application:
    name: gateway
  cloud:
#    discovery:
#      enabled: false
    config:
      enabled: false
    kubernetes:
      enabled: true
      config:
        enabled: true
        name: gateway-config
        namespace: default
      loadbalancer:
        mode: service
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/booking-service/(?<segment>.*), /$\{segment}
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking-service
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/tracking-service/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false