apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-deployment
  labels:
    app: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
      - name: tracking
        image: moonsungkim/tracking-amd
        imagePullPolicy: Always #comment except minikube
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actutator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10     