spring:
  config:
    activate:
      on-profile: kubernetes
  application:
    name: tracking-service
  cloud:
    config:
      enabled: false
    kubernetes:
      enabled: true
      config:
        enabled: true
        name: tracking-config
        namespace: default
      loadbalancer:
        mode: service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
greeting:
  message: "Tracking-Service in Kubernetes!"