spring:
  application:
    name: tracking-service
  config:
    activate:
      on-profile: kubernetes

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
greeting:
  message: "Tracking-Service in Kubernetes!"