server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moonstar0331/spring-cloud-kubernetes
          default-label: main
